export interface GeographyHierarchy {
  [continent: string]: {
    [country: string]: string[];
  };
}

export const TRAVEL_GEOGRAPHY: GeographyHierarchy = {
  "Asia": {
    "India": [
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Delhi",
      "Jammu and Kashmir",
      "Ladakh",
      "Lakshadweep",
      "Puducherry"
    ],
    "Japan": ["Tokyo", "Kyoto", "Osaka", "Hokkaido", "Okinawa", "Nara", "Fukuoka", "Miyagi", "Kanagawa", "Hiroshima", "Chiba", "Saitama", "Shizuoka", "Aichi", "Hyogo", "Nagano", "Gifu", "Niigata", "Ishikawa", "Pradesh Shiga"],
    "China": ["Beijing", "Shanghai", "Sichuan", "Yunnan", "Guangdong", "Fujian", "Hunan", "Shaanxi", "Zhejiang", "Jiangsu", "Tibet", "Xinjiang", "Guangxi", "Chongqing", "Hubei", "Anhui", "Henan", "Hainan", "Inner Mongolia"],
    "Thailand": ["Bangkok", "Phuket", "Chiang Mai", "Krabi", "Chon Buri", "Surat Thani", "Phang Nga", "Mae Hong Son", "Ayutthaya", "Prachuap Khiri Khan", "Chiang Rai", "Nakhon Ratchasima", "Sukhothai"],
    "South Korea": ["Seoul", "Busan", "Jeju", "Gyeonggi", "Gangwon", "Incheon", "Gyeongsang", "Jeolla", "Chungcheong", "Daegu", "Daejeon", "Ulsan", "Gwangju"],
    "Vietnam": ["Hanoi", "Ho Chi Minh City", "Da Nang", "Quang Nam", "Lao Cai", "Lam Dong", "Kien Giang", "Thua Thien Hue", "Ninh Binh", "Khanh Hoa", "Can Tho", "Hai Phong", "Quang Ninh"],
    "Indonesia": ["Bali", "Jakarta", "West Java", "Central Java", "East Java", "Yogyakarta", "Lombok", "North Sumatra", "East Kalimantan", "South Sulawesi", "Riau Islands", "West Nusa Tenggara", "Papua"],
    "Malaysia": ["Kuala Lumpur", "Penang", "Selangor", "Sabah", "Sarawak", "Pahang", "Melaka", "Johor", "Kedah", "Perak", "Terengganu", "Kelantan", "Negeri Sembilan"],
    "Singapore": ["Central Region", "East Region", "North Region", "North-East Region", "West Region"],
    "Philippines": ["Metro Manila", "Cebu", "Palawan", "Davao Region", "Benguet", "Malay (Boracay)", "Bohol", "Cavite", "Pampanga", "Iloilo", "Siargao Island", "Laguna"],
    "Sri Lanka": ["Colombo", "Western Province", "Central Province (Kandy)", "Southern Province (Galle)", "Sabaragamuwa", "Eastern Province", "Northern Province", "North Central Province"],
    "Nepal": ["Bagmati (Kathmandu)", "Gandaki (Pokhara)", "Lumbini", "Koshi", "Janakpur", "Karnali", "Sudurpashchim"],
    "UAE": ["Abu Dhabi", "Dubai", "Sharjah", "Ajman", "Umm Al Quwain", "Ras Al Khaimah", "Fujairah"],
    "Saudi Arabia": ["Riyadh", "Makkah (Mecca)", "Madinah", "Eastern Province", "Asir", "Tabuk", "Al-Qassim", "Hail", "Jazan"],
    "Taiwan": ["Taipei", "New Taipei", "Kaohsiung", "Taichung", "Tainan", "Hualien", "Yilan", "Nantou", "Pingtung", "Kinmen"],
    "Maldives": ["Malé", "Baa Atoll", "Ari Atoll", "Kaafu Atoll", "Addu Atoll", "Dhaalu Atoll", "Lhaviyani Atoll"],
    "Bangladesh": ["Dhaka Division", "Chittagong Division", "Sylhet Division", "Rajshahi Division", "Khulna Division", "Barisal Division", "Rangpur Division"]
  },
  "Europe": {
    "France": ["Île-de-France", "Provence", "French Riviera", "Brittany", "Normandy", "Loire Valley", "Alsace", "Occitanie", "Corsica", "Auvergne-Rhône-Alpes", "Burgundy", "Hauts-de-France", "Nouvelle-Aquitaine"],
    "Italy": ["Tuscany", "Sicily", "Lombardy", "Veneto", "Amalfi Coast", "Lazio", "Campania", "Piedmont", "Puglia", "Sardinia", "Emilia-Romagna", "Umbria", "Liguria", "Trentino-Alto Adige", "Abruzzo", "Aosta Valley", "Friuli-Venezia Giulia"],
    "Spain": ["Catalonia", "Andalusia", "Madrid", "Balearic Islands", "Valencia", "Galicia", "Basque Country", "Canary Islands", "Castile and León", "Aragon", "Asturias", "Murcia", "Extremadura", "Cantabria", "La Rioja"],
    "Germany": ["Bavaria", "Berlin", "Saxony", "Hamburg", "Baden-Württemberg", "Hesse", "Rhineland-Palatinate", "Lower Saxony", "North Rhine-Westphalia", "Schleswig-Holstein", "Brandenburg", "Thuringia", "Mecklenburg-Vorpommern"],
    "United Kingdom": ["England", "Scotland", "Wales", "Northern Ireland", "Greater London", "Highlands", "Cornwall", "Yorkshire", "Cotswolds", "Bermuda", "Devon", "Lake District", "Orkney Islands"],
    "Greece": ["Attica", "Central Macedonia", "Crete", "South Aegean", "Ionian Islands", "Peloponnese", "Thessaly", "Epirus", "Western Greece", "Mount Athos", "Cyclades", "Sporades", "Rhodes"],
    "Portugal": ["Lisbon", "Porto", "Algarve", "Madeira", "Azores", "Alentejo", "Central Portugal", "Norte", "Minho", "Douro Valley"],
    "Switzerland": ["Zurich", "Geneva", "Bern", "Vaud", "Lucerne", "Ticino", "Grisons", "Valais", "Uri", "Interlaken Region", "Zermatt Region", "Appenzell", "Basel-Stadt"],
    "Netherlands": ["North Holland", "South Holland", "Utrecht", "North Brabant", "Gelderland", "Friesland", "Overijssel", "Limburg", "Zeeland", "Groningen"],
    "Austria": ["Vienna", "Salzburg", "Tyrol", "Styria", "Upper Austria", "Carinthia", "Lower Austria", "Vorarlberg", "Burgenland"],
    "Ireland": ["Leinster (Dublin)", "Munster (Cork/Kerry)", "Connacht (Galway)", "Ulster (Donegal)", "County Clare", "County Mayo", "County Sligo", "County Wicklow"],
    "Sweden": ["Stockholm", "Västra Götaland (Gothenburg)", "Skåne (Malmö)", "Uppsala", "Norrbotten (Lapland)", "Gotland", "Öland", "Dalarna"],
    "Norway": ["Oslo", "Vestland (Bergen)", "Troms og Finnmark", "Viken", "Rogaland", "Nordland (Lofoten)", "Møre og Romsdal", "Trøndelag", "Svalbard"],
    "Turkey": ["Istanbul", "Anatolia", "Aegean", "Mediterranean", "Cappadocia", "Black Sea", "Marmara", "Pamukkale Region", "Antalya Coast"],
    "Croatia": ["Split-Dalmatia", "Istria", "Dubrovnik-Neretva", "Zagreb", "Zadar", "Lika-Senj", "Šibenik-Knin", "Kvarner Gulf"],
    "Poland": ["Masovian (Warsaw)", "Lesser Poland (Krakow)", "Pomeranian (Gdansk)", "Lower Silesian", "Silesian", "West Pomeranian", "Masurian Lake District"],
    "Iceland": ["Capital Region (Reykjavik)", "Southern Region", "Western Region", "Northeastern Region", "Westfjords", "Eastfjords", "Reykjanes Peninsula"],
    "Belgium": ["Brussels-Capital Region", "Flemish Region (Flanders)", "Walloon Region (Wallonia)", "Antwerp", "Bruges Region", "Ghent Area"],
    "Denmark": ["Capital Region of Denmark (Copenhagen)", "Central Denmark Region", "North Denmark Region", "Region Zealand", "Region of Southern Denmark", "Faroe Islands"],
    "Finland": ["Uusimaa", "Lapland", "Southwest Finland", "Pirkanmaa", "Åland Islands", "North Karelia", "Lakeland Region"]
  },
  "Africa": {
    "Egypt": ["Cairo", "Giza", "Luxor", "Red Sea", "Alexandria", "Aswan", "South Sinai", "Matrouh", "Dakahlia", "Suez", "Fayoum Oasis"],
    "South Africa": ["Western Cape", "Gauteng", "KwaZulu-Natal", "Eastern Cape", "Mpumalanga", "Free State", "Limpopo", "North West", "Northern Cape"],
    "Morocco": ["Marrakesh-Safi", "Casablanca-Settat", "Fes-Meknes", "Tanger-Tetouan-Al Hoceima", "Rabat-Sale-Kenitra", "Souss-Massa", "Draa-Tafilalet", "Oriental", "Chefchaouen Region", "Sahara Desert Dunes"],
    "Kenya": ["Nairobi", "Mombasa", "Rift Valley", "Central", "Coast", "Eastern", "Nyanza", "Western", "Masai Mara Eco-Reserves", "Laikipia Plateau"],
    "Nigeria": ["Lagos", "Abuja (FCT)", "Kano", "Rivers", "Enugu", "Oyo", "Delta", "Kaduna", "Anambra", "Ogun", "Cross River (Calabar)", "Plateau (Jos)"],
    "Tanzania": ["Zanzibar", "Dar es Salaam", "Arusha", "Kilimanjaro", "Manyara", "Pwani", "Mwanza", "Dodoma", "Serengeti Plains", "Ngorongoro Crater Area"],
    "Mauritius": ["Port Louis", "Black River", "Flacq", "Pamplemousses", "Plaines Wilhems", "Savanne", "Grand Port", "Rivière du Rempart"],
    "Seychelles": ["Mahé", "Praslin", "La Digue", "Outer Islands", "Silhouette Island", "Aldabra Atoll"],
    "Ethiopia": ["Addis Ababa", "Amhara", "Oromia", "Tigray", "Southern Nations", "Afar Region", "Harari"],
    "Ghana": ["Greater Accra", "Ashanti", "Western Region", "Volta Region", "Central Region", "Northern Region", "Eastern Region"],
    "Madagascar": ["Analamanga", "Atsinanana", "Diana (Nosy Be)", "Sava", "Boeny", "Atsimo-Andrefana", "Anosy (Taolagnaro)"],
    "Tunisia": ["Tunis", "Sousse", "Hammamet Region", "Djerba", "Carthage District", "Tozeur (Sahara Gateway)", "Sidi Bou Said Line"],
    "Uganda": ["Central Region (Kampala)", "Western Region", "Eastern Region", "Northern Region", "Bwindi Impenetrable Forest Zone", "Queen Elizabeth Biosphere"]
  },
  "North America": {
    "USA": ["California", "New York", "Florida", "Hawaii", "Texas", "Washington", "Illinois", "Nevada", "Arizona", "Colorado", "Oregon", "Massachusetts", "Utah", "Alaska", "Montana", "North Carolina", "Virginia", "Pennsylvania", "Wyoming", "Georgia", "Maine", "Tennessee", "New Mexico", "Louisiana", "Michigan"],
    "Canada": ["Ontario", "Quebec", "British Columbia", "Alberta", "Nova Scotia", "Manitoba", "Saskatchewan", "New Brunswick", "Newfoundland and Labrador", "Yukon", "Northwest Territories", "Nunavut", "Prince Edward Island"],
    "Mexico": ["Quintana Roo", "Jalisco", "Oaxaca", "Mexico City", "Baja California", "Yucatan", "Guerrero", "Guanajuato", "Chiapas", "Yucatán", "Nuevo León", "Michoacán", "Nayarit (Riviera)", "Puebla", "Campeche"],
    "Costa Rica": ["San Jose", "Alajuela", "Guanacaste", "Puntarenas", "Limon", "Heredia", "Cartago", "Monteverde Cloud Reserves"],
    "Jamaica": ["Kingston", "Saint Ann", "Saint James", "Westmoreland", "Portland", "Saint Andrew", "Saint Elizabeth", "Trelawny"],
    "Dominican Republic": ["Santo Domingo", "La Altagracia", "Puerto Plata", "Samaná", "Santiago", "San Cristóbal", "Barahona", "La Romana"],
    "Panama": ["Panama Province", "Chiriquí", "Bocas del Toro", "Coclé", "Colón", "San Blas Islands(Guna Yala)", "Herrera"],
    "Bahamas": ["New Providence (Nassau)", "Grand Bahama", "Abaco Islands", "Exuma", "Eleuthera", "Andros Island", "San Salvador"],
    "Guatemala": ["Guatemala Department", "Sacatepéquez (Antigua)", "Sololá (Atitlán)", "Petén (Tikal)", "Quetzaltenango", "Izabal", "Alta Verapaz"],
    "Cuba": ["Havana", "Matanzas (Varadero)", "Villa Clara", "Santiago de Cuba", "Cienfuegos", "Pinar del Río", "Sancti Spíritus (Trinidad)"]
  },
  "South America": {
    "Brazil": ["Rio de Janeiro", "São Paulo", "Bahia", "Amazonas", "Minas Gerais", "Pernambuco", "Santa Catarina", "Paraná", "Ceará", "Goiás", "Rio Grande do Sul", "Mato Grosso", "Distrito Federal (Brasília)", "Rio Grande do Norte", "Alagoas"],
    "Argentina": ["Buenos Aires", "Patagonia", "Mendoza", "Salta", "Córdoba", "Santa Cruz", "Tierra del Fuego", "Jujuy", "Río Negro", "Chubut", "Misiones (Iguazu)", "Neuquén", "San Juan"],
    "Peru": ["Cusco", "Lima", "Arequipa", "Ica", "La Libertad", "Puno", "Ancash", "Loreto", "San Martín", "Madre de Dios (Amazon)", "Lambayeque"],
    "Chile": ["Santiago", "Valparaiso", "Magallanes", "Antofagasta", "Los Lagos", "Atacama", "Coquimbo", "Araucanía", "Tarapacá", "Easter Island (Rapa Nui)", "Aysén"],
    "Colombia": ["Bogotá", "Antioquia", "Bolívar", "Valle del Cauca", "Quindío", "Cundinamarca", "Caldas", "Magdalena", "Santander", "San Andrés y Providencia", "Boyacá", "Meta"],
    "Ecuador": ["Pichincha", "Guayas", "Galápagos", "Azuay", "Manabí", "Imbabura", "Tungurahua", "Napo (Amazon Rainforest)", "Loja"],
    "Bolivia": ["La Paz", "Santa Cruz", "Potosí", "Cochabamba", "Sucre", "Oruro", "Beni", "Tarija"],
    "Uruguay": ["Montevideo", "Maldonado (Punta del Este)", "Rocha", "Colonia", "Canelones", "Salto", "Rocha Coastline"],
    "Venezuela": ["Capital District (Caracas)", "Miranda", "Nueva Esparta (Margarita)", "Bolívar (Canaima)", "Mérida", "Falcon (Morrocoy)", "Aragua"],
    "Paraguay": ["Asunción (Distrito Capital)", "Central", "Alto Paraná (Ciudad del Este)", "Itapúa", "Cordillera", "Chaco Region"]
  },
  "Oceania": {
    "Australia": ["New South Wales", "Queensland", "Victoria", "Western Australia", "South Australia", "Tasmania", "Northern Territory", "ACT", "Whitsundays", "Great Barrier Reef Zone"],
    "New Zealand": ["Auckland", "Canterbury", "Otago", "Wellington", "Bay of Plenty", "Waikato", "Northland", "Taranaki", "Tasman", "Southland", "Marlborough", "West Coast", "Hawke's Bay"],
    "Fiji": ["Viti Levu", "Vanua Levu", "Taveuni", "Mamanuca Islands", "Yasawa Islands", "Lomaiviti Group"],
    "Papua New Guinea": ["National Capital District", "Central", "Morobe", "Madang", "East New Britain", "Milne Bay", "New Ireland"],
    "Samoa": ["Upolu", "Savai'i", "Apia Region", "Manono Island"],
    "Tonga": ["Tongatapu", "Vava'u", "Ha'apai", "'Eua Island"],
    "French Polynesia (Tahiti)": ["Tahiti", "Bora Bora", "Moorea", "Marquesas Islands", "Raiatea", "Tuamotu Archipelago", "Huahine"],
    "Cook Islands": ["Rarotonga", "Aitutaki", "Mangaia", "Atiu", "Mauke"],
    "Solomon Islands": ["Guadalcanal", "Western Province", "Malaita", "Choiseul", "Isabel Province"]
  },
  "Antarctica": {
    "Ross Dependency": ["McMurdo Station", "Scott Base", "Ross Ice Shelf", "Dry Valleys", "Mount Erebus Peak"],
    "Antarctic Peninsula": ["Hope Bay", "Petermann Island", "Deception Island", "Trinity Peninsula", "Palmer Station", "Port Lockroy", "Anvers Island", "Lemaire Channel"],
    "Adélie Land": ["Dumont d'Urville Station", "Astrolabe Glacier"],
    "Queen Maud Land": ["Troll Station", "Tor Station", "Novolazarevskaya Station", "Maitri Indian Outpost", "Sowa Station Cluster"],
    "Marie Byrd Land": ["Amundsen-Scott South Pole Station (Sector)", "Mount Sidley", "Executive Committee Range", "Siple Dome Explorer Camp"],
    "Ellsworth Land": ["Vinson Massif Base", "Patriot Hills", "Union Glacier Camp", "Sentinel Range Ascent"]
  }
};
